import = [
  #"~/.config/alacritty/themes/themes/ashes_dark.toml",
  #"~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml",
  "~/.config/alacritty/themes/themes/ayu_mirage.toml",
]

[font]
  normal = { family = "Hack Nerd Font Mono", style = "Regular" }
  bold = { family = "Hack Nerd Font Mono", style = "Bold" }
  italic = { family = "Hack Nerd Font Mono", style = "Italic" }
  bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }
  size = 13

[window]
  # The value `0.0` is completely transparent and `1.0` is opaque.
  blur = true
  opacity = 0.55
  decorations = "Buttonless"
  padding = { x = 4, y = 4 }
  dynamic_padding = true

[[keyboard.bindings]]
chars = "\u0001"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Command"

[shell]
  program = "/bin/zsh"
#args = ["-l","-c","tmux"]
  args = ["-l"]

